<?php
/**
 * WordPress Configuration Generator
 * Generates wp-config.php based on environment variables
 */

// Get environment variables
$db_host = getenv('WORDPRESS_DB_HOST') ?: 'mysql';
$db_name = getenv('WORDPRESS_DB_NAME') ?: 'wordpress';
$db_user = getenv('WORDPRESS_DB_USER') ?: 'wordpress';
$db_password = getenv('WORDPRESS_DB_PASSWORD') ?: 'wordpress';
$db_prefix = getenv('WORDPRESS_DB_PREFIX') ?: 'wp_';
$db_port = getenv('WORDPRESS_DB_PORT') ?: '3306';
$db_ssl = filter_var(getenv('WORDPRESS_DB_SSL'), FILTER_VALIDATE_BOOLEAN) ?: false;
$wp_debug = filter_var(getenv('WORDPRESS_DEBUG'), FILTER_VALIDATE_BOOLEAN) ?: false;
$behind_proxy = filter_var(getenv('WORDPRESS_BEHIND_PROXY'), FILTER_VALIDATE_BOOLEAN) ?: false;
$proxy_ssl = filter_var(getenv('WORDPRESS_PROXY_SSL'), FILTER_VALIDATE_BOOLEAN) ?: false;
$wp_language = getenv('WORDPRESS_LANGUAGE') ?: 'es_MX';
$wp_auto_update = filter_var(getenv('WORDPRESS_AUTO_UPDATE'), FILTER_VALIDATE_BOOLEAN) ?: false;
$wp_site_url = getenv('WORDPRESS_SITE_URL') ?: '';

// Get wp-content directory settings
$wp_content_rel_dir = getenv('WORDPRESS_CONTENT_DIR') ?: '/wp-content';
$wp_content_abs_dir = (substr($wp_content_rel_dir, 0, 1) !== '/') 
    ? "/var/www/html$wp_content_rel_dir" 
    : $wp_content_rel_dir;

// Prepare values for config
$debug_value = $wp_debug ? 'true' : 'false';
$auto_update_value = $wp_auto_update ? 'true' : "'minor'";
$site_url_check = !empty($wp_site_url) ? true : false;

// Generate unique keys and salts
$characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_ []{}<>~`+=,.;:/?|';
$keys = array(
    'AUTH_KEY',
    'SECURE_AUTH_KEY',
    'LOGGED_IN_KEY',
    'NONCE_KEY',
    'AUTH_SALT',
    'SECURE_AUTH_SALT',
    'LOGGED_IN_SALT',
    'NONCE_SALT'
);

$salts = '';
foreach ($keys as $key) {
    $salt = '';
    for ($i = 0; $i < 64; $i++) {
        $salt .= $characters[rand(0, strlen($characters) - 1)];
    }
    $salts .= "define('" . $key . "', '" . $salt . "');\n";
}

// MySQL SSL configuration
$mysql_ssl_config = '';
if ($db_ssl) {
    $mysql_ssl_config = <<<EOT
// MySQL SSL Configuration
define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
EOT;
}

// Proxy settings
$proxy_config = '';
if ($behind_proxy) {
    $proxy_config = <<<EOT
// Proxy configuration
if (isset(\$_SERVER['HTTP_X_FORWARDED_FOR'])) {
    \$_SERVER['REMOTE_ADDR'] = \$_SERVER['HTTP_X_FORWARDED_FOR'];
}

EOT;

    if ($proxy_ssl) {
        $proxy_config .= <<<EOT
// SSL behind proxy
if (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    \$_SERVER['HTTPS'] = 'on';
}

EOT;
    }
}

// Site URL configuration
$site_url_config = '';
if ($site_url_check) {
    $site_url_config = <<<EOT
// Site URL settings
define('WP_SITEURL', '{$wp_site_url}');
define('WP_HOME', '{$wp_site_url}');

EOT;
}

// Custom content directory configuration
$content_url = $site_url_check ? "$wp_site_url$wp_content_rel_dir" : $wp_content_rel_dir;
$content_dir_config = <<<EOT
// Custom content directory
define('WP_CONTENT_DIR', '{$wp_content_abs_dir}');
define('WP_CONTENT_URL', '{$content_url}');

EOT;

// Create wp-config.php file
$config = <<<EOT
<?php
/**
 * WordPress Configuration - Generated by Docker container
 */

// ** Database settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', '{$db_name}');

/** Database username */
define('DB_USER', '{$db_user}');

/** Database password */
define('DB_PASSWORD', '{$db_password}');

/** Database hostname */
define('DB_HOST', '{$db_host}:{$db_port}');

/** Database charset to use in creating database tables */
define('DB_CHARSET', 'utf8mb4');

/** The database collate type. Don't change this if in doubt */
define('DB_COLLATE', '');

/** MySQL database table prefix */
\$table_prefix = '{$db_prefix}';

{$mysql_ssl_config}

/**#@+
 * Authentication unique keys and salts.
 *
 * Change these to different unique phrases! You can generate these using
 * the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}.
 *
 * You can change these at any point in time to invalidate all existing cookies.
 * This will force all users to have to log in again.
 */
{$salts}
/**#@-*/

{$proxy_config}

/**
 * WordPress debugging mode.
 */
define('WP_DEBUG', {$debug_value});

// WordPress language
define('WPLANG', '{$wp_language}');

// Auto-updates
define('WP_AUTO_UPDATE_CORE', {$auto_update_value});

{$site_url_config}
{$content_dir_config}
/** Absolute path to the WordPress directory */
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

/** Sets up WordPress vars and included files */
require_once ABSPATH . 'wp-settings.php';
EOT;

// Write configuration to file
file_put_contents('/var/www/html/wp-config.php', $config);

echo "WordPress configuration file generated successfully.\n";