name: Build and Publish WordPress Docker Image
on:
  push:
    branches: [ "main" ]
  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:
env:
  # Ajusta estos valores según tu imagen
  APP_NAME: "wordpress-nginx"
  ORGANIZATION: "byteaid"
  WP_VERSION: '6.7.2'
  PHP_VERSION: '8.1'
  ALPINE_VERSION: '3.19'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Get tag version
      id: version
      run: |
        echo "VERSION=wp${WP_VERSION}-php${PHP_VERSION}-alpine${ALPINE_VERSION}-$(date +'%Y.%m.%d').${{ github.run_number }}" >> $GITHUB_OUTPUT
        echo "SHORT_VERSION=wp${WP_VERSION}-php${PHP_VERSION}" >> $GITHUB_OUTPUT
    
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.ORGANIZATION }}/${{ env.APP_NAME }}:latest
          ${{ env.ORGANIZATION }}/${{ env.APP_NAME }}:${{ steps.version.outputs.VERSION }}
          ${{ env.ORGANIZATION }}/${{ env.APP_NAME }}:${{ steps.version.outputs.SHORT_VERSION }}
        cache-from: type=registry,ref=${{ env.ORGANIZATION }}/${{ env.APP_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.ORGANIZATION }}/${{ env.APP_NAME }}:buildcache,mode=max
